### ISSUE TITLE
can't open app in macos 15

### ISSUE THREAD

**Issue by gkl1368** [nrlquaker/winbox-mac#144]
can't open app in macos 15

**Comment by tdabasinskas** [comment]
Yes, I can confirm the same - it's not opening on MacOS 15 Beta.

**Comment by nrlquaker** [comment]
Betas are not supported.

**Comment by belthesar** [comment]
Just to add a little color here - 

Developer Preview / Public Beta versions of macOS aren't supported for this project, because they are frequently moving targets. Historically, many programs do not work appropriately, especially on the first Developer Preview version of macOS, so if stability is essential to you, _I highly recommend avoiding installing Developer Preview versions of macOS on your primary / sole Mac_. 

In addition, we're at the behest of upstream WINE support for the vast majority of work on the project. We'll be keeping tabs on [WINE's Bugzilla](https://bugs.winehq.org/describecomponents.cgi?product=Wine) to see if there's anything here we need to be aware of.

**Comment by tdabasinskas** [comment]
Thanks for providing more details, @belthesar.

I switched from using `winbox-mac` to simply using official winbox.exe via Wine directly - works without any issues on the current Developer Preview.

**Comment by nrlquaker** [comment]
@tdabasinskas what wine are you using? The one in brew?

**Comment by tdabasinskas** [comment]
> @tdabasinskas what wine are you using? The one in brew?

I actually used [WineSkin](https://github.com/Gcenx/WineskinServer) (from Brew) with `WS12WineCX64Bit23.7.1-2` engine with `Wineskin-3.0.3` wrapper.

**Comment by gkl1368** [comment]
Also use crossover to open winbox is  worked

**Comment by kotori2** [comment]
For quick fixes: you can literally just replace `wine` that comes with this package to the latest ones. 
Install `wine-stable` from homebrew (currently `9.0-3`) and replace all 3 folders under `/Applications/Winbox-mac.app/Contents/Resources/` with `/Applications/Wine Stable.app/Contents/Resources/wine/`. Not sure if there's any side effects but it just works for me.

**Comment by nrlquaker** [comment]
@belthesar can you update to the latest wine?

**Comment by gkl1368** [comment]
It works after replace 3 folders with wine 9.0-3.

**Comment by belthesar** [comment]
HI folks. I was on vacation last week. I'll see about getting a Wine 9 test build going, however without @Gcenx providing a slim version, the bundle size will increase significantly unless I can figure out a manual way to create an equivalent slim Wine distribution.

**Comment by nrlquaker** [comment]
@belthesar the last time I've [updated wine](https://github.com/nrlquaker/winbox-mac/commit/fe21f010fbc107727659640171911d35c5b907f4) I used the [Gcenx/macOS_Wine_builds](https://github.com/Gcenx/macOS_Wine_builds). And manually updated `wine.inf` to include the following https://github.com/nrlquaker/winbox-mac/blob/3a5037e72ffa419b9d020f7c2077b461deb75c26/Winbox-mac.app/Contents/Resources/wine/share/wine/wine.inf#L555-L564
Maybe @Gcenx can help with minimal build again.
