### ISSUE TITLE
Dark Mode winbox 

### ISSUE THREAD

**Issue by kubert96** [nrlquaker/winbox-mac#149]
Hello, 

is there way to make winbox run dark mode? 

I know that this is just running Winbox exe in some wine. 

But there is way to remap keys. So i think it shoud be posible.

**Comment by belthesar** [comment]
It is possible to apply custom themes to Wine, but that's not something I feel we could reasonably support. It looks like that some folks have gotten custom themes to work with Wine, but the effect is not universal (see https://forum.mikrotik.com/viewtopic.php?p=844900#p845289). Because I don't think we can reasonably add support for it, I'm going to close this issue, but you are welcome to try to implement it within your own copy of Winbox-mac, and/or submit a pull request for us to review adding support.
