### ISSUE TITLE
3.28.1 resize issues on 2020 M1 MBP 13"

### ISSUE THREAD

**Issue by tomikaa87** [nrlquaker/winbox-mac#74]
**Checklist**

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [x] I made sure this is not the original Winbox issue.

**Describe the bug**
With the latest update and the enabled retina mode, the window can only be resized to certain dimensions and after that, it's content stays the same. The remaining space is filled with black color. In that state, the mouse clicks are "misaligned" (probably the position of the cursor is "scaled back" to the size of the content), and I must click next to or below an item to activate it. I've tried the method mentioned in the release notes multiple times without luck. I've even tried to start the application twice after removing the data folder, but it didn't help. Sometimes moving the window away from its default position helps, but not always.

**To Reproduce**
1. Open the application
2. Resize the window beyond the point where the black area is visible

**Expected behavior**
The content resizes properly.

**Screenshots**
<img width="1326" alt="Screenshot 2021-06-30 at 19 13 28" src="https://user-images.githubusercontent.com/15613825/124003855-adae2800-d9d7-11eb-8e4f-3ce4a0d443a9.png">

**Desktop (please complete the following information):**
 - macOS version: 11.4
 - macOS language: English US
 - Winbox-mac version 3.28.1
 - Winbox version 3.28

**Comment by tomikaa87** [comment]
> Is it M1 mac?

It is, a 2020 MacBook Pro M1 13".

**Comment by mikegleasonjr** [comment]
Try to `alt-tab` to another application and go back to Winbox, can you resize it now?

**Comment by tomikaa87** [comment]
> Try to `alt-tab` to another application and go back to Winbox, can you resize it now?

Yes, it helps. What I see when I do that:
* Start the application -> the window has the default size
* Resize -> black borders appear
* Alt-tab -> The window jumps back to its original size
* Resize -> works normally

**Comment by mikegleasonjr** [comment]
Yeah I had this behavior for a loooong time on a non-M1 MacBook Pro. I can't remember if it is fixed now for me, I think so. So I don't know what causing it on an M1. So at least now you have a workaround...

**Comment by nrlquaker** [comment]
Are you using DUET or Sidecar? If yes, its wine [issue](https://bugs.winehq.org/show_bug.cgi?id=48896).

**Comment by nrlquaker** [comment]
Closing as there is no response.

**Comment by tomikaa87** [comment]
> Are you using DUET or Sidecar? If yes, its wine [issue](https://bugs.winehq.org/show_bug.cgi?id=48896).

No, I use only the main screen, so it’s a different issue.

**Comment by Lillecarl** [comment]
So I don't have quite the same issue, but if i don't resize Winbox to fullscreen when in the connection screen I'm unable to click outside the original connect windows's size.

When building a plugin for https://github.com/mRemoteNG/mRemoteNG and https://github.com/Terminals-Origin/Terminals i realized that WinBox does a weird thing. So a Windows window has something called a HWND, which is a Windows Window Handle. A process in Windows has a primary HWND, what WinBox does when it connect is that it replaces the pointer of the primary window handle with a new one (The actiual winbox UI).

This causes problems for people using RoyalTS, since RoyalTS doesn't reread the primary HWND (we use window title tracking for this purpose where i work, shitty workaround).

Anyways, I believe that by doing these weirdo things WinBox breaks some assumptions Wine has regarding window handles and sizing them.

MacBook 2016

**Comment by Lillecarl** [comment]
After resetting my Wine with 

```
rm -rf /Applications/Wine*
rm -rf ~/.wine/
```

I'm now experiencing the same issue. Updated winbox within the app itself to 3.29.

**Comment by azizolious** [comment]
I am facing the same issue and resizing, and the application does not remember the size and position of the window upon the next launch. 

Moreover, you cannot customize column settings in any window from simple queue to DHCP Server window.

**Comment by Talhazzers** [comment]
I'm having the same issue in the current version.
